version: '3.3'
services:
    home-assistant:
        volumes:
            - ./config/home-assistant:/config
        image: homeassistant/home-assistant
        ports:
          - "8123:8123"

    mqtt:
        image: eclipse-mosquitto
        volumes:
            - ./config/mqtt/config:/mosquitto/config
    ozwdaemon:
        volumes:
            - './config/ozwdaemon/config:/opt/ozw/config'
        environment:
            - MQTT_SERVER=mqtt
        image: 'openzwave/ozwdaemon:latest'
